---
title: "Data Core Supplement Numbers"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    theme: cerulean
    highlight: zenburn
---

# Load Requirements

## Load Useful Libraries

```{r}
# USEFUL LIBRARIES ----
library(dplyr)
library(stringr)
library(knitr)
library(kableExtra)
```

## Load Useful Variables

```{r}
# USEFUL VARS ----
`%>%` <- `%>%`
source('~/Desktop/config.R')
rm(BOX_CLIENT_ID); rm(BOX_CLIENT_SECRET); rm(BOX_REDIRECT_URI)
rm(REDCAP_DATA_REQUESTS_TOKEN)

## switch to access API (TRUE) or not (FALSE)
get_api_data <- TRUE
```

## Load Useful Helper Functions

```{r}
# USEFUL HELPER FUNCTIONS ----
remove_NAs <- function(x) {
  if (is.vector(x)) return(x[!is.na(x)])
  else stop('x is not a vector')
}
```


# Get Data

## Select Useful Fields

```{r}
fields_ms_raw <- c("subject_id"
                   , "exam_date"
                   , "sex_value")
fields_ms <- fields_ms_raw %>% paste(collapse = ",")
```

## Retrieve Data via REDCap API

```{r}
if (get_api_data) {
  json_ms <- rc_api_get(
    uri    = REDCAP_API_URI,
    token  = REDCAP_API_TOKEN_MINDSET,
    fields = fields_ms
  )
}
```

```{r}
df_ms <- jsonlite::fromJSON(json_ms) %>% na_if("")
```


# Process Data

## Clean Data

Remove any records where `exam_date` is `NA`.

```{r}
df_ms <- df_ms %>% 
  filter(!is.na(exam_date)) %>% 
  filter(!is.na(sex_value))
```


# Summarize Data

## Total N

```{r}
df_ms %>% 
  distinct(subject_id) %>% 
  summarize(n = n())
```

## N by Sex

```{r}
df_ms %>% 
  arrange(subject_id, exam_date) %>% 
  distinct(subject_id, .keep_all = TRUE) %>% 
  group_by(sex_value) %>% 
  summarize(n = n())
```

## N by Visit Count

```{r}
df_ms %>% 
  arrange(subject_id, exam_date) %>% 
  mutate(visit_unit = 1L) %>% 
  group_by(subject_id) %>% 
  mutate(visit_cnt = cumsum(visit_unit)) %>% 
  ungroup() %>% 
  group_by(visit_cnt) %>% 
  summarize(n = n())
```


```
###@    #==--  :  --==#    @##==---==##@##==---==##@    #==--  :  --==#    @###
#==##@    #==-- --==#    @##==---==##@   @##==---==##@    #==-- --==#    @##==#
#--==##@    #==-==#    @##==---==##@   #   @##==---==##@    #==-==#    @##==--#
#=---==##@    #=#    @##==---==##@    #=#    @##==---==##@    #=#    @##==---=#
##==---==##@   #   @##==---==##@    #==-==#    @##==---==##@   #   @##==---==##
#@##==---==##@   @##==---==##@    #==-- --==#    @##==---==##@   @##==---==##@#
#  @##==---==##@##==---==##@    EXTRA  :  SPACE    @##==---==##@##==---==##@  #
#@##==---==##@   @##==---==##@    #==-- --==#    @##==---==##@   @##==---==##@#
##==---==##@   #   @##==---==##@    #==-==#    @##==---==##@   #   @##==---==##
#=---==##@    #=#    @##==---==##@    #=#    @##==---==##@    #=#    @##==---=#
#--==##@    #==-==#    @##==---==##@   #   @##==---==##@    #==-==#    @##==--#
#==##@    #==-- --==#    @##==---==##@   @##==---==##@    #==-- --==#    @##==#
###@    #==--  :  --==#    @##==---==##@##==---==##@    #==--  :  --==#    @###
#==##@    #==-- --==#    @##==---==##@   @##==---==##@    #==-- --==#    @##==#
#--==##@    #==-==#    @##==---==##@   #   @##==---==##@    #==-==#    @##==--#
#=---==##@    #=#    @##==---==##@    #=#    @##==---==##@    #=#    @##==---=#
##==---==##@   #   @##==---==##@    #==-==#    @##==---==##@   #   @##==---==##
#@##==---==##@   @##==---==##@    #==-- --==#    @##==---==##@   @##==---==##@#
#  @##==---==##@##==---==##@    EXTRA  :  SPACE    @##==---==##@##==---==##@  #
#@##==---==##@   @##==---==##@    #==-- --==#    @##==---==##@   @##==---==##@#
##==---==##@   #   @##==---==##@    #==-==#    @##==---==##@   #   @##==---==##
#=---==##@    #=#    @##==---==##@    #=#    @##==---==##@    #=#    @##==---=#
#--==##@    #==-==#    @##==---==##@   #   @##==---==##@    #==-==#    @##==--#
#==##@    #==-- --==#    @##==---==##@   @##==---==##@    #==-- --==#    @##==#
###@    #==--  :  --==#    @##==---==##@##==---==##@    #==--  :  --==#    @###
```
